Feat/challenge functions 1
Enma1920/05-javascript-functions pull request #1
Opened 2023-11-18 16:29 UTC by Enma1920

json's and yalm docs are correctly pushe but I don't know why github doesn't recognize the workflow of lint and it is everything updated correctly, nevertheless I did the exercises and I pushed everything but I have this issue of the workflow

2023-11-19 09:19 UTC, tictools requested changes

2023-11-19 09:19 UTC, tictools commented on .github/workflows/pipeline.yaml
> +        run: npm run lint:fix
FIX: lint, not lint:fix

2023-11-19 09:19 UTC, tictools commented on exercise_01/index.js
FIX: separete blocks with empty lines

2023-11-19 09:19 UTC, tictools commented on exercise_03/index.js
FIX: separete blocks with empty lines

2023-11-19 09:19 UTC, tictools commented on exercise_04/isGreaterThan.js
> +  const result = value > threshold ? true : false;
This is redundant.

```suggestion
  const result = value > threshold;
```

2023-11-19 09:19 UTC, tictools commented on exercise_04/index.js
FIX: separete blocks with empty lines

2023-11-19 09:19 UTC, tictools commented on exercise_05/isAdditionGreaterThanFifty.js
> +  return summand1 + summand2 >= 50 ? true : false;
Redundant.

```suggestion
  return summand1 + summand2 >= 50;
```

2023-11-19 09:19 UTC, tictools commented on exercise_06/checkCollectionHasElements.js
Your logic is checking that collection has no elements, but you must check if it has got them.

⚠️ Use strict equality comparator (`===`) instead of equality comparator (`==`)

FIX: rethink logic

2023-11-19 09:19 UTC, tictools commented on exercise_07/index.js
FIX: separete blocks with empty lines

2023-11-20 18:38 UTC, adlomo23 commented
Good job! If you keep working like this, you will recive awesome results!

2023-11-20 18:43 UTC, adlomo23 approved these changes

2023-11-21 19:03 UTC, tictools approved these changes

2023-11-21 19:04 UTC, merged